#!/bin/bash

add() {
    cp -r $* './BUFFER'
}

list() {
    if [[ -n $1 ]]; then
        tree -a --noreport topic.*
    else
        tree -a --noreport topic.[!_]*
    fi
}

_prefix() {
    local topic
    for topic in $*; do
        case $topic in
            topic.*) echo $topic ;;
            *) echo "topic.$topic" ;;
        esac
    done
}

save() {
    mv "./BUFFER/*" "./BUFFER/*" `_prefix $1`
}

_green() {
    echo -e "\033[32m$1\033[0m"
}

apply() {
    local files=(`find $(_prefix $*) -not -type d`) afters=()
    local f; for f in ${files[@]}; do
        case $f in
            topic.*/ROOT/*)
                after=${f#topic.*/ROOT}
                _green $after
            ;;
            topic.*/*)
                 after=$HOME/${f#topic.*/}
                _green '~/'${f#topic.*/}
            ;;
        esac
        afters=(${afters[@]} $after)
    done
    local permit; read -p "Process? [Y/n] " permit
    case $permit in
        Y | y | [Yy][Ee][Ss] | '') ;;
        *) echo "Aborted."; exit 1 ;;
    esac
    local i; for i in ${!files[@]}; do
        # absolute path
        ln -sf `readlink -f ${files[$i]}` ${afters[$i]}
    done
}



: << EOF
for j in $*; do
    case $i in
        -*) ;;
        *) args=(${args[@]} $i) ;;
    esac
done
EOF

main() {
    local todo display_all
    for i in $*; do
        case $i in
            --*)
                case $i in
                    --add) todo=add ;;
                    --save) todo=save ;;
                    --list) todo=list ;;
                    --all) display_all=true ;;
                esac
            ;;
            -*)
                i=${i:1}
                for ((j=0; j<${#i}; j++)); do
                    case ${i:$j:$j+1} in
                        a) todo=add ;;
                        s) todo=status_ ;;
                        S) todo=save ;;
                        l) todo=list ;;
                        A) display_all=true ;;
                    esac
                done
            ;;
            *) targets=(${targets[@]} $i) ;;
        esac
    done
    if [[ -z $todo ]]; then
        if [[ -z $targets ]]; then
            exit 1
        fi
        todo=apply
    fi
    $todo $display_all ${targets[@]}
}

main $*
