#!/bin/bash

add() {
    cp -r $* './BUFFER'
}

list() {
    if [[ -z $* ]]; then
        if [[ $display_all ]]; then
            tree -a --noreport topic.*
        else
            tree -a --noreport topic.[!_]*
        fi
    else
        tree -a --noreport `_prefix $*`
    fi
}

_prefix() {
    local topic
    for topic in $*; do
        case $topic in
            topic.*) echo $topic ;;
            *) echo "topic.$topic" ;;
        esac
    done
}

save() {
    mv "./BUFFER/*" "./BUFFER/.*" `_prefix $1`
}

_green() {
    echo -e "\033[32m$1\033[0m"
}

apply() {
    local files=(`find $(_prefix $*) -not -type d`) afters=()
    local f; for f in ${files[@]}; do
        case $f in
            topic.*/ROOT/*)
                after=${f#topic.*/ROOT}
                _green $after
            ;;
            topic.*/*)
                 after=$HOME/${f#topic.*/}
                _green '~/'${f#topic.*/}
            ;;
        esac
        afters=(${afters[@]} $after)
    done
    local permit; read -p "Process? [Y/n] " permit
    case $permit in
        Y | y | [Yy][Ee][Ss] | '') ;;
        *) echo "Aborted."; exit 1 ;;
    esac
    local i; for i in ${!files[@]}; do
        # absolute path
        ln -sf `readlink -f ${files[$i]}` ${afters[$i]}
    done
}



main() {
    local todo
    while true; do
        # _green $1
        case $1 in
            -a | --add) todo=add; shift ;;
            -S | --save) todo=save; shift ;;
            -s | --status) todo=status; shift ;;
            -l | --list) todo=list; shift ;;
            -A | --all) display_all='true'; shift ;;
            --) shift; break ;;
            *) echo "Unknown option: $1"; exit 1 ;;
        esac
    done
    if [[ -z $todo ]]; then
        if [[ -z $@ ]]; then
            exit 1
        fi
        todo=apply
    fi
    $todo $@
}

OPT=`getopt -o aS:slA -l add,save:,status,list,all -- "$@"` || exit 1
eval set -- "$OPT"
unset OPT
main $@
